### ISSUE TITLE
failed to initialize

### ISSUE THREAD

**Issue by sidju** [OpenVoiceOS/ovos-skill-easter-eggs#5]
12:20:30.936 - mycroft.skills.core:load_skill:144 - ERROR - Failed to load skill: skill_easter_eggs.jarbasal
Traceback (most recent call last):
File "/home/sid/assistant/mycroft-core/mycroft/skills/core.py", line 115, in load_skill
('.py', 'rb', imp.PY_SOURCE)
File "/usr/lib/python3.6/imp.py", line 235, in load_module
return load_source(name, filename, file)
File "/usr/lib/python3.6/imp.py", line 172, in load_source
module = _load(spec)
File "<frozen importlib._bootstrap>", line 684, in _load
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 674, in exec_module
File "<frozen importlib._bootstrap_external>", line 781, in get_code
File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/opt/mycroft/skills/skill_easter_eggs.jarbasal/__init__.py", line 330
print "Invalid stardate format"
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Invalid stardate format")?

I'll trust you to do the poking that is needed.

**Comment by JarbasAl** [comment]
skill was done for python2, mycroft is now python 3

**Comment by jshep321** [comment]
Made some quick updates and mostly works on my install (picroft)

**Comment by jshep321** [comment]
Update:  I forked it and merged my new Diehard themed holiday skill here: https://github.com/jshep321/skill_easter_eggs

**Comment by JarbasAl** [comment]
hello @jshep321 , would you like to be the new maintainer of this skill? i would be happy to archive this repo and link to yours, i only request you submit it to the marketplace!

**Comment by jshep321** [comment]
Hmmm, just playing around now as a side hobby but since the interest seems low, sure.  I'll not touch your German locale however as High School Deutsche is quite useless.  I probably won't submit to the marketplace as including these mp3's might cause DMCA bots to wake up, even though these are most likely covered under US fair use laws.

**Comment by krisgesling** [comment]
Hi there, Jarbas asked for my thoughts on this from Mycroft's perspective.

Assuming all the files are short audio snippets and not used for commercial profit, I think this fits within the terms of fair use under US copyright law. As such we would accept it into the Mycroft Skills Marketplace if you chose to submit it. In the unlikely event that a copyright holder disagreed with this, we would have that conversation with them.

**Comment by mikejgray** [comment]
Skill has been ported to Python 3 and the latest OVOS standards, closing this issue
